version: '3.9'
services:
  db:
    image: mysql:8.0
    # not recommended for production
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanbex
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  backend:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:kanbex@db:3306/kanbex
      - JWT_SECRET=14A0D118257AF1EEDCE6F2D4734D5FFEAFB055752C7024610C06541A7D9DC226
    entrypoint: ["./docker/docker-entrypoint.local.sh"]
volumes:
  mysql_data:
